apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-volume
  labels:
    type: local
spec:
  storageClassName: slow
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/share/Experiments/simulator"
