apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  revisionHistoryLimit: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      volumes:
        - name: share
          persistentVolumeClaim:
              claimName: share-claim
      containers:
      - name: simulator
        image: git.uni-due.de:6666/embedded-systems/elastic-node/simulator:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "64Gi"
            cpu: "15"
        volumeMounts:
          - name:  share
            mountPath:  /output
        # ports:
        # - containerPort: <Port>
      imagePullSecrets:
        - name: regcred
