apiVersion: batch/v1
kind: Job
metadata:
  generateName: simulator
#  name: simulator-test
spec:
  template:
    spec:
      volumes:
        - name: share-nfs
          nfs:
            server: 192.168.200.30
            path: /experiments
#          persistentVolumeClaim:
#              claimName: share-claim
      containers:
      - name: simulator
        image: git.uni-due.de:6666/embedded-systems/elastic-node/simulator:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: share-nfs
            mountPath: /output/
        resources:
          requests:
            memory: "2Gi"
            cpu: "250m"
          limits:
            memory: "64Gi"
            cpu: "16"
      imagePullSecrets:
      - name: regcred
      restartPolicy: Never
#  ttlSecondsAfterFinished: 604800 # 7 days
