apiVersion: batch/v1
kind: Job
metadata:
  # generateName: simulator
  name: simulator-test
spec:
  ttlSecondsAfterFinished: 604800 # 7 days 
  template:
    spec:
      volumes:
        - name: share
          persistentVolumeClaim:
              claimName: share-claim
      containers:
      - name: simulator
        image: 134.91.56.21:6666/embedded-systems/elastic-node/simulator:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "64Gi"
            cpu: "4"
        volumeMounts:
          - name:  share
            mountPath:  /output
      restartPolicy: Never
        # ports:
        # - containerPort: <Port>
      imagePullSecrets:
        - name: regcred
