apiVersion: batch/v1
kind: Job
metadata:
  name: simulator
spec:
  # revisionHistoryLimit: 1
  # strategy:
  #   type: "Recreate"
  # selector:
  #   matchLabels:
  #     app: simulator
  template:
    # metadata:
    #   labels:
    #     app: simulator
    spec:
      volumes:
        - name: share
          persistentVolumeClaim:
              claimName: share-claim
      containers:
      - name: simulator
        image: git.uni-due.de:6666/embedded-systems/elastic-node/simulator:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "64Gi"
            cpu: "15"
        volumeMounts:
          - name:  share
            mountPath:  /output
      restartPolicy: Never
        # ports:
        # - containerPort: <Port>
      imagePullSecrets:
        - name: regcred
