apiVersion: batch/v1
kind: Job
metadata:
#  generateName: simulator
  name: simulator-job
spec:
  template:
    spec:
      volumes:
        - name: share-nfs
#          nfs:
#            server: 192.168.200.30
#            path: /experiments
          persistentVolumeClaim:
              claimName: share-claim
      containers:
      - name: simulator
        image: alwynburger/simulator:experiment
#        image: git.uni-due.de:6666/embedded-systems/elastic-node/simulator:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: share-nfs
            mountPath: /output/
        resources:
          requests:
            memory: "2Gi"
            cpu: "16"
          limits:
            memory: "16Gi"
            cpu: "64"
      imagePullSecrets:
      - name: regcred
      restartPolicy: Never
#  ttlSecondsAfterFinished: 604800 # 7 days
